# Generated by Django 4.0.4 on 2022-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_adress', models.EmailField(max_length=40)),
                ('company', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
