# Generated by Django 4.0.4 on 2022-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_create_date_alter_contact_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
